name: CI
on:
   push:
    branches: [ "main" ]
jobs:
 
  build:
     runs-on: ubuntu-latest
     steps:
   
       - uses: actions/checkout@v4
       - name: Run a one-line script
         run: echo Hello, world!
       - name: Run a multi-line script
         run: |
          echo Add other actions to build,
          echo test, and deploy your project.
test:
runs-on: Unbuntu lastest
      steps:
      - name: Check- Uptime
      run: Uptime
      -name: Cpu Info
      run: nproc
      -name Kernel info
      run: uname -r
